### ISSUE TITLE
Bigger Tinderbox pictures

### ISSUE THREAD

**Issue by betovelandia** [crockpotveggies/tinderbox#6]
I wonder if it is possible to make the pictures on that page bigger:

```css
.feed-element img.img-circle,
.dropdown-messages-box img.img-circle {
    width: 38px;
    height: 38px;
}
```

And make them say 100 px ?
